### ISSUE TITLE
vagrant ssh asks for a password for trinity@localhost

### ISSUE THREAD

**Issue by abshkbh** [ops-class/vagrant#8]
Somehow I am asked for a password even though this shouldn't be the case. While running vagrant up I do run into this error -

 ==> default: Configuration file '/etc/sudoers'  
861 ==> default:  ==> Modified (by you or by a script) since installation.  
862 ==> default:  ==> Package distributor has shipped an updated version.  
863 ==> default:    What would you like to do about it ?  Your options are:  
864 ==> default:     Y or I  : install the package maintainer's version  
865 ==> default:     N or O  : keep your currently-installed version  
866 ==> default:       D     : show the differences between the versions  
867 ==> default:       Z     : start a shell to examine the situation  
868 ==> default:  The default action is to keep your current version.  
869 ==> default: **\* sudoers (Y/I/N/O/D/Z) [default=N] ?  
870 ==> default: Configuration file '/etc/sudoers'  
871 ==> default:  ==> Modified (by you or by a script) since installation.  
872 ==> default:  ==> Package distributor has shipped an updated version.  
873 ==> default:    What would you like to do about it ?  Your options are:  
874 ==> default:     Y or I  : install the package maintainer's version  
875 ==> default:     N or O  : keep your currently-installed version  
876 ==> default:       D     : show the differences between the versions  
877 ==> default:       Z     : start a shell to examine the situation  
878 ==> default:  The default action is to keep your current version.  
879 ==> default: **\* sudoers (Y/I/N/O/D/Z) [default=N] ?  
880 ==> default: dpkg: error processing package sudo (--configure):

**Comment by abshkbh** [comment]
Just to clarify I can't login because I don't know what the password is.

**Comment by aseemrb** [comment]
@abshkbh This is caused because of the confirmation dialog that appears, asking what to do when configuration files are modified. There's no flag in the provision script file here to auto-confirm that. You can use [my version of the provision script file](https://github.com/aseemraj/vagrant/blob/config-change-prompt-fix/.provision/provision.sh) to solve the problem for now.

Replace the file `.provision/provision.sh` with the new file from the above link, and it should work fine. Now you should be able to log in without a password.

**Comment by abshkbh** [comment]
That worked. Seeing the diff between the files how are tmux etc being installed ? The original provision file "apt-get"ed them explicitly.

**Comment by aseemrb** [comment]
tmux etc. are still being installed explicitly. I have only added the `-o Dpkg::Options::="--force-confnew"` which upon receiving this popup of config file changes auto chooses the `Y or I` option to install the new version instead of keeping the old version, and hence the input is not expected at that choice, so the bash script runs well.

**Comment by abshkbh** [comment]
Oops, I forgot to scroll to the right and see those packages there in the command. Thanks !!

**Comment by aseemrb** [comment]
@abshkbh you should keep the issue open as it needs fixing in the main repo.

**Comment by markphelps** [comment]
@aseemraj thanks for this! why not make a PR?

**Comment by aseemraj** [comment]
@markphelps sure! I'll send a PR soon.

**Comment by aseemrb** [comment]
@markphelps done! #9 is a potential PR.
